name: Sync Upstream

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/samdiefenbacher/watchman-test" 
  # Optional, defaults to main
  UPSTREAM_BRANCH: "main"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "main"
  # Optional merge arguments
  REBASE_ARGS: "-Xours"
  # Git email
  EMAIL: "sam@orevillestudios.com"
  # Git name
  NAME: "Sam Diefenbacher"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Github Fork
        run: |
          # Add upstream incase enviroment doesn't have it configured
          git remote add upstream ${{env.UPSTREAM_URL}}
          
          # Configure git email
          git config --global user.email ${{env.EMAIL}}
          
          # Configure git name
          git config --global user.name ${{env.NAME}}
          
          # Checkout sync branch
          git checkout ${{env.DOWNSTREAM_BRANCH}}
          
          # Fetcg upstream repo
          git fetch upstream
          
          git rebase upstream/main ${{env.REBASE_ARGS}}
          
          git push -f
          
      - name: Merge to dev
        run: |
          # Fetch
          git fetch
          
          # Checkout dev
          git checkout --track origin/dev
          
          # Rebase changse and apply our commits on top
          git rebase origin/${{env.DOWNSTREAM_BRANCH}} -Xours
          
          git push -f
